name: spotify_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  flutter_svg: ^1.0.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  flutter_bloc: ^8.1.6
  firebase_core: ^3.3.0
  firebase_auth:
  get_it: ^7.7.0
  dartz:
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/getstartedimage.jpg
    - assets/images/image2.png
    - assets/images/bille_siginin_page.png
    - assets/vectors/Vector.svg
    - assets/vectors/Sun 1.svg
    - assets/vectors/Moon.svg
    - assets/vectors/Union.svg
    - assets/vectors/Union2.svg
    - assets/vectors/Union2.svg
    - assets/images/bille_root.png
    - assets/vectors/Frame 2.svg
    - assets/images/rootdetail.svg

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 600
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
 
    