// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDap5F6vyZCaXzZcgeGbNu1y5BMdUA9KmU',
    appId: '1:338020247567:web:6c7a6e7a07cb9d20bbdb7a',
    messagingSenderId: '338020247567',
    projectId: 'keda-d9c75',
    authDomain: 'keda-d9c75.firebaseapp.com',
    storageBucket: 'keda-d9c75.appspot.com',
    measurementId: 'G-XL4M6XD88Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Dzs6HvUlpy5IRNj4KqUExSaRQPrxXb0',
    appId: '1:338020247567:android:81ef225c72c7c553bbdb7a',
    messagingSenderId: '338020247567',
    projectId: 'keda-d9c75',
    storageBucket: 'keda-d9c75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA91p2NcZUV_kAk9W-p43uHEIMOERGBOLU',
    appId: '1:338020247567:ios:361caa353c6b311abbdb7a',
    messagingSenderId: '338020247567',
    projectId: 'keda-d9c75',
    storageBucket: 'keda-d9c75.appspot.com',
    iosBundleId: 'com.example.spotifywithoutfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA91p2NcZUV_kAk9W-p43uHEIMOERGBOLU',
    appId: '1:338020247567:ios:361caa353c6b311abbdb7a',
    messagingSenderId: '338020247567',
    projectId: 'keda-d9c75',
    storageBucket: 'keda-d9c75.appspot.com',
    iosBundleId: 'com.example.spotifywithoutfire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDap5F6vyZCaXzZcgeGbNu1y5BMdUA9KmU',
    appId: '1:338020247567:web:f33bd6906ae684f7bbdb7a',
    messagingSenderId: '338020247567',
    projectId: 'keda-d9c75',
    authDomain: 'keda-d9c75.firebaseapp.com',
    storageBucket: 'keda-d9c75.appspot.com',
    measurementId: 'G-1QNGJNT4Q4',
  );

}